### ISSUE TITLE
qq音乐安卓：如何获取master_key

### ISSUE THREAD

**Issue by hz-zhangfc** [nukemiko/libtakiyasha#3]
QQ 音乐移动客户端，版本 11.5.5 及之后: 无内嵌密钥，需要从客户端数据库文件中获取主密钥 master_key。
在那个文件中，如何获取master_key呢？

**Comment by nukemiko** [comment]
这需要你自己去研究了。我没有接触过这个/这些文件，不知道怎么提取。而且“客户端数据库文件”的存在是其他人通过反编译客户端逻辑得出来的。

另外，如果你只是想解密下载的文件，可以用这个项目：[zjns/QMHelper](https://github.com/zjns/QMHelper)
