### ISSUE TITLE
能否提供一下解码的例子，例如解码.ncm为.mp3

### ISSUE THREAD

**Issue by GitJoBo** [nukemiko/libtakiyasha#6]

**Comment by nukemiko** [comment]
```python
from libtakiyasha import ncm

with ncm.NCM.open(<your_ncm_file>, core_key=<YourCoreKeyBytes>) as ncmfile:
    with open(ncmfile.source.with_suffix('.' + ncmfile.ncm_tag.format) as outputfile:
        for blk in ncmfile:
            outputfile.write(blk)
```

把 `<>` 括起来的内容换成你自己的文件和密钥。

**Comment by GitJoBo** [comment]
ncm可以了，万分感谢。qmc的方便提供下吗？ 我用下面这种方式不行
```
def decodQmc(inPath: str, outPath: str) -> int:
    print("dddd inPath = " + inPath + "; outPath = " + outPath)
    try:
        filething, fileInfo = libtakiyasha210.qmc.probe_qmc(inPath)
        with fileInfo.open(inPath,
                           b'\x6a',
                           b'\x33\略\x28',
                           b'\x2A\略\x54') as qmcFile:
            with open(outPath, "wb") as outputFile:
                for blk in qmcFile:
                    outputFile.write(blk)
        return 0
    except:
        print('出错了T_T')
        return 1
```

**Comment by nukemiko** [comment]
> ncm可以了，万分感谢。qmc的方便提供下吗？ 我用下面这种方式不行
> 
> ```
> def decodQmc(inPath: str, outPath: str) -> int:
>     print("dddd inPath = " + inPath + "; outPath = " + outPath)
>     try:
>         filething, fileInfo = libtakiyasha210.qmc.probe_qmc(inPath)
>         with fileInfo.open(inPath,
>                            b'\x6a',
>                            b'\x33\略\x28',
>                            b'\x2A\略\x54') as qmcFile:
>             with open(outPath, "wb") as outputFile:
>                 for blk in qmcFile:
>                     outputFile.write(blk)
>         return 0
>     except:
>         print('出错了T_T')
>         return 1
> ```

```pycon
>>> import sys
>>> from libtakiyasha import qmc
>>> filepath, fileinfo = qmc.probe_qmc(<Yout QMC file path>)
>>>
```
不能直接通过 `fileinfo` 打开文件，你要根据 `fileinfo` 对象的类型来判断怎么打开：
```pycon
>>> if isinstance(fileinfo, qmc.QMCv1FileInfo):
...     qmc_opener = QMCv1.open
...     qmc_opener_args = (fileinfo,)
...     qmc_opener_kwargs = {'mask': <YourMaskBytes>}
... elif isinstance(fileinfo, qmc.QMCv2FileInfo):
...     qmc_opener = QMCv2.open
...     qmc_opener_args = (fileinfo,)
...     qmc_opener_kwargs = {'core_key': <YourCoreKeyBytes>, 'garble_key1': <YourGarbleKey1OrNone>, 'garble_key2': <YourGarbleKey2OrNone>}
... else:
...     print(f'错误：不支持的文件类型：{filepath}')
...     sys.exit(1)
...
>>> with qmc_opener(*qmc_opener_args, **qmc_opener_kwargs) as qmcfile:
...     [...]  # 剩下的知道怎么写了吧
...            # 注意：你需要探测解密后数据的头部以决定输出文件的扩展名
...
>>>
```
另外，如果你用的是 IDE，那么你应该很容易看到文档，内有使用示例。

**Comment by GitJoBo** [comment]
感谢大佬解答，正确的YourGarbleKey1OrNone格式是这样写吗?(b'\x33\略\x28');
注意：你需要探测解密后数据的头部以决定输出文件的扩展名 这里输出文件扩展名写死mp3不行吗？  
方便加下qq吗？927735928

**Comment by nukemiko** [comment]
@GitJoBo 
> 感谢大佬解答，正确的YourGarbleKey1OrNone格式是这样写吗?(b'\x33\略\x28');

是要这样写，而且只接受可以直接转换为 `bytes` 类型的对象作为密钥。（如果要输入字符串，需要先 `encode()`）

> 注意：你需要探测解密后数据的头部以决定输出文件的扩展名 这里输出文件扩展名写死mp3不行吗？

当然可以写死扩展名，不过你要是输入 mflac/mgg 文件，输出文件的格式（flac/ogg）与扩展名不一致，可能会导致某些场合无法打开和播放。

如果不方便通过输出数据的头部判断，也可以通过输入文件的扩展名 `qmcfile.source.suffix` 判断输出文件的扩展名。
